export const characters = [
    {
        name: "Golden Frieza",
        superMove: "Death Beam",
        strength: 9200,
        speed: 9000,
        energy: 9500,
        defense: 8500,
        fighter: "./images/characters/frieza.png",
        background: "./images/background/frieza.jpg",
    },
    {
        name: "Ultra Instinct Goku",
        superMove: "Kamehameha",
        strength: 9800,
        speed: 10000,
        energy: 9500,
        defense: 9000,
        fighter: "./images/characters/goku.png",
        background: "./images/background/goku.jpg",
    },
    {
        name: "Krillin",
        superMove: "Destructo Disc",
        strength: 4500,
        speed: 5500,
        energy: 6000,
        defense: 4000,
        fighter: "./images/characters/krillin.png",
        background: "./images/background/krillin.jpg",
    },
    {
        name: "Super Saiyan Blue Vegeta",
        superMove: "Final Flash",
        strength: 9300,
        speed: 9200,
        energy: 8800,
        defense: 9000,
        fighter: "./images/characters/vegeta.png",
        background: "./images/background/vegeta.jpg",
    },
    {
        name: "Yamcha",
        superMove: "Wolf Fang Fist",
        strength: 3000,
        speed: 4000,
        energy: 3500,
        defense: 2500,
        fighter: "./images/characters/yamcha.png",
        background: "./images/background/yamcha.jpg",
    },
];
